[package]
name = "libbpf-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
libbpf-rs = "0.24.4"
log = "0.4.22"
simple_logger = "5.0.0"

[build-dependencies]
libbpf-cargo = "0.24.4"
